config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#index'

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'



  namespace :admin do

    resources :posts
    resources :settings, only: [:new, :create, :edit, :update]
    resources :dashboard, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :messages, only: [:index, :show, :update, :destroy]
    resources :visitors, only: [:index, :destroy]
    resources :comments, only: [:index, :update, :destroy ]
    resources :tags, except: [:index]
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators,  only: [:index, :edit, :update]
  end

    resources :posts, only: [:index, :show]
    resources :messages, only: [:new, :create]
  match 'dismiss_all_notifications',  to: 'admin/notifications#delete_all', via: :delete

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :visitor
  has_many :notifications, as: :notifiable

  def self.matching_fullname_or_message params
   joins(:visitor).where("fullname LIKE ?  OR message LIKE ?", "%#{params}%", "%#{params}%")
end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :visitor

  def self.matching_fullname_or_content params
    joins(:visitor).where("fullname LIKE ? OR content LIKE ?", "%#{params}%", "%#{params}%")
end
  def mark_read
    update(status: true) if status == false
end
end

app/models/moderator.rb
class Moderator < ActiveRecord::Base
    has_secure_password
    has_many :posts

 validates :fullname, presence: true
 validates :username, presence: true, format:  {with: /@/, message: 'is not valid'}
 validates :password, presence:true
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :moderator
  has_many :post_tags, dependent: :destroy
  has_many :tags, through:  :post_tags
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true



#refactoring
  def self.matching_title_or_content search
    where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%")
end

end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ActiveRecord::Base
def self.site_name
    Setting.first.site_name
end
def self.post_per_page
    Setting.first.post_per_page
end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :posts, through:  :post_tags
    validates :name, presence: true
    def in_use?
        PostTag.exists?(tag_id: self.id)
    end
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
    has_many :notifications, as: :notifiable, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :messages, dependent: :destroy
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
    @posts = Post.last 5
    @comments =Comment.last 5
    @visitors = Visitor.last 5
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.where(publish: true).order(id: :desc).page(params[:page]).per(Setting.post_per_page)
  end

  def show
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
    def message_weight message
        message.status == false ? 'font-weight:bold' : 'font-weight:normal'
end
 def build_read_status_link message
    if message.status == true
        link_to 'Unread', admin_message_path(message, status: false), method: :put
    else
        link_to 'Read', admin_message_path(message, status: true), method: :put
    end
end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
    def create_deletable_button tag

                 if tag.in_use?
                  link_to '#' do
                          content_tag(:button, 'Delete', class: 'disabled')
                         end
                          else
                  link_to  admin_tag_path(tag), method:  :delete do
                    content_tag(:button, 'Delete')
                   end
                  end
              end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def status_converter(status, truthy: 'Active', falsey: 'Pending')
        if status
            truthy
        else
            falsey
        end
    end
    def time_ago time_ago
        "#{time_ago_in_words(time)} ago"
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/dashboard/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BLOG</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= stylesheet_link_tag('backend', :media=> 'all') %>
    <%= stylesheet_link_tag('article', :media=> 'all') %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'article', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'backend', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid display-table">

        <!-- side menu -->
       <%= render "admin/side_menu" %>

          <div class="col-md-10 col-sm-11 display-table-cell vertical-align">
       <div class="row">

               <header id="nav-header" class="clearfix">
                <div class="col-md-5">

                  <nav class="navbar-default pull-left">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="side-menu">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </nav>
                 <input type="text" class="hidden-sm hidden-xs" id="header-search-field" placeholder="search for anythings..">
                </div>
                  <div class="col-md-7">
                    <ul class="pull-right">
                      <li id="welcome" class="hidden-xs">welcome to administrator area</li>
                       <li class="fixed-width">
                        <a href="#">
                          <span class="glyphicon glyphicon-bell" aria-hidden="true"></span>
                          <span class="label label-warning">3</span>
                        </a>
                      </li>

                       <li class="fixed-width">
                        <a href="#">
                          <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                          <span class="label label-message">3</span>
                        </a>
                      </li>

                       <li>
                        <a href="#" class="logout">
                          <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                        log-out
                        </a>
                      </li>

                    </ul>

                  </div>
               </header>
           </div>

               <div id="dashboard-con">
                <div class="row">
                  <div class="col-md-6 dashboard-left-cell">
                    <div class="admin-content-con">
                      <header class="clearfix">
                        <h5 class="pull-left">article</h5>
                        <%= link_to 'Create new post', new_admin_post_path %>
                      </header>
                      <table class="table table-striped">
                        <thead>
                          <tr>
                            <th>title</th>
                            <th>replies</th>
                            <th>date</th>
                            <th>actions</th>
                          </tr>
                        </thead>
                        <tbody>
                              <% @posts.each do |post| %>
                          <tr>
                            <td> <%= truncate(post.title, length: 40, separator: ' ' )%></td>
                             <td><%post.comments.count %></td>
                              <td> <%= time_ago_in_words post.created_at %> ago</td>
                               <td>

                                      <%= link_to 'Edit', edit_admin_post_path(post) %>
                                      <%= link_to 'View', admin_post_path(post) %>
                                      <%= link_to 'Del', admin_post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %>
                                          button">delete</a>
                               </td>
                          </tr>

                      <% end %>

                        </tbody>
                      </table>

                    </div>

                  </div>
                   <div class="col-md-6 dashboard-right-cell">
                    <div class="admin-content-con">
                      <header>
                        <h5>comments</h5>
                      </header>
                      <% @comments.each do |comment| %>
                      <div class="comment-head-dash">

                        <div class="commenter-name-dash">comment</div>

                      </div>
                    <p class="comment-dash"><%= truncate(comment.message, length: 125, separtor: ' ') %>
                   </p>
                   <small class="comment-date-dash"><%= time_ago_in_words comment.created_at %></small>
                    <hr>
                 <%= link_to 'list all comments', admin_posts_path %>
                    </div>
    <% end %>
                  </div>
                </div>
               </div>

               <div class="row">
                 <div class="col-md-12">
                   <div class="admin-content-con clearfix">
                     <header>
                       <h5>Commenters</h5>
                     </header>
                     <table class="table table-striped col-sm-1">
                       <thead>
                         <tr>
                           <th>#</th>
                            <th>Full Name</th>
                             <th>Email</th>
                              <th>Status</th>
                              <th>Created</th>
                              <th>Actions</th>
                         </tr>
                       </thead>
                       <tbody>
                          <% @visitors.each_with_index do |visitor, index| %>
                         <tr>
                           <td><%= index + 1 %></td>
                              <td><%= visitor.fullname %></td>
                                 <td><%= visitor.email %></td>

                                    <td><%= time_ago_in_words visitor.created_at %> ago</td>
                                    <td>
                                      <%= link_to 'Delete', admin_visitor_path(visitor), method: :delete, data: {confirm: 'Are you sure?'} %>
                                    </td>
                         </tr>
<% end %>

                       </tbody>
                     </table>
                   </div>
                 </div>
               </div>

           <div class="row">
            <footer id="admin-footer"  class="clearfix">
              <div class="pull-left"><b>copyright </b>&copy; 2016</div>
              <div class="pull-right">Mnrt</div>
            </footer>

          </div>

</div>


  </div>
</div>



</body>