config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#index'

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'



  namespace :admin do

    resources :posts
    resources :settings, only: [:new, :create, :edit, :update]
    resources :dashboard, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :messages, only: [:index, :show, :update, :destroy]
    resources :visitors, only: [:index, :destroy]
    resources :comments, only: [:index, :update, :destroy ]
    resources :tags, except: [:index]
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators,  only: [:index, :edit, :update]
  end

    resources :posts, only: [:index, :show]
    resources :messages, only: [:new, :create]
  match 'dismiss_all_notifications',  to: 'admin/notifications#delete_all', via: :delete

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :visitor
  has_many :notifications, as: :notifiable

  def self.matching_fullname_or_message params
   joins(:visitor).where("fullname LIKE ?  OR message LIKE ?", "%#{params}%", "%#{params}%")
end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :visitor

  def self.matching_fullname_or_content params
    joins(:visitor).where("fullname LIKE ? OR content LIKE ?", "%#{params}%", "%#{params}%")
end
  def mark_read
    update(status: true) if status == false
end
end

app/models/moderator.rb
class Moderator < ActiveRecord::Base
    has_secure_password
    has_many :posts

 validates :fullname, presence: true
 validates :username, presence: true, format:  {with: /@/, message: 'is not valid'}
 validates :password, presence:true
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :moderator
  has_many :post_tags, dependent: :destroy
  has_many :tags, through:  :post_tags
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true



#refactoring
  def self.matching_title_or_content search
    where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%")
end

end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ActiveRecord::Base
def self.site_name
    Setting.first.site_name
end
def self.post_per_page
    Setting.first.post_per_page
end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :posts, through:  :post_tags
    validates :name, presence: true
    def in_use?
        PostTag.exists?(tag_id: self.id)
    end
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
    has_many :notifications, as: :notifiable, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.where(publish: true).order(id: :desc).page(params[:page]).per(Setting.post_per_page)
  end

  def show
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
    def message_weight message
        message.status == false ? 'font-weight:bold' : 'font-weight:normal'
end
 def build_read_status_link message
    if message.status == true
        link_to 'Unread', admin_message_path(message, status: false), method: :put
    else
        link_to 'Read', admin_message_path(message, status: true), method: :put
    end
end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
    def create_deletable_button tag

                 if tag.in_use?
                  link_to '#' do
                          content_tag(:button, 'Delete', class: 'disabled')
                         end
                          else
                  link_to  admin_tag_path(tag), method:  :delete do
                    content_tag(:button, 'Delete')
                   end
                  end
              end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def status_converter(status, truthy: 'Active', falsey: 'Pending')
        if status
            truthy
        else
            falsey
        end
    end
    def time_ago time_ago
        "#{time_ago_in_words(time)} ago"
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/_side_menu.html.erb
  <div class="row display-table-row">
          <div class="col-md-2 col-sm-1 hidden-xs display-table-cell vertical-align" id="side-menu">
            <h1 class="hidden-xs hidden-sm">Navigation</h1>
            <ul>
              <li class="link">
                 <%=link_to admin_dashboard_index_path do %>
                  <span class="glyphicon glyphicon-th" aria-hidden="true"</span>
                  <span class="hidden-sm hidden-xs">Dashboard</span>
               <% end %>
              </li>

              <li class="link active">
                <a href="#collapse-post" data-toggle="collapse" aria-controls="collapse-post">
                  <span class="glyphicon glyphicon-list-alt" aria-hidden="true"</span>
                    <span class="hidden-sm hidden-xs">article</span>
                    <span class="label label-success hidden-sm hidden-xs"> 20</span>
                  </a>

                  <ul class ="collapse collapseable" id="collapse-post">
                    <li><a href="#">Create new</a></li>
                    <li><a href="#">View Article</a></li>
                  </ul>
                </li>

                <li class="link">
                <a href="#collapse-comments" data-toggle="collapse" aria-controls="collapse-comments">
                  <span class="glyphicon glyphicon-pencil" aria-hidden="true"</span>
                    <span class="hidden-sm hidden-xs">Comments</span>

                  </a>

                  <ul class ="collapse collapseable" id="collapse-comments">
                    <li><a href="#">Approved

                    <span class="label label-success pull-right" hidden-sm hidden-xs> 10</span>

                    </a></li>

                    <li><a href="#">Unapproved

                    <span class="label label-warning pull-right" hidden-sm hidden-xs> 10</span>

                    </a></li>

                  </ul>
                </li>

                <li class="link">
                <a href="#">
                  <span class="glyphicon glyphicon-user" aria-hidden="true"</span>
                  <span class="hidden-sm hidden-xs">Commenter</span>
                </a>
              </li>
                <li class="link">
                <%= link_to new_admin_tag_path do %>
                  <span class="glyphicon glyphicon-tags" aria-hidden="true"</span>
                  <span class="hidden-sm hidden-xs">Tags</span>
                <% end %>
              </li>

                <li class="link settings-btn">
                 <%= link_to new_admin_setting_path do %>
                  <span class="glyphicon glyphicon-cog" aria-hidden="true"</span>
                  <span class="hidden-sm hidden-xs">Settings</span>
                <% end %>
              </li>
            </ul>
          </div>