config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#index'

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'



  namespace :admin do

    resources :posts
    resources :settings, only: [:new, :create, :edit, :update]
    resources :dashboard, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :messages, only: [:index, :show, :update, :destroy]
    resources :visitors, only: [:index, :destroy]
    resources :comments, only: [:index, :update, :destroy ]
    resources :tags, except: [:index]
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators,  only: [:index, :edit, :update]
  end

    resources :posts, only: [:index, :show]
    resources :messages, only: [:new, :create]
  match 'dismiss_all_notifications',  to: 'admin/notifications#delete_all', via: :delete

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :visitor
  has_many :notifications, as: :notifiable

  def self.matching_fullname_or_message params
   joins(:visitor).where("fullname LIKE ?  OR message LIKE ?", "%#{params}%", "%#{params}%")
end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :visitor

  def self.matching_fullname_or_content params
    joins(:visitor).where("fullname LIKE ? OR content LIKE ?", "%#{params}%", "%#{params}%")
end
  def mark_read
    update(status: true) if status == false
end
end

app/models/moderator.rb
class Moderator < ActiveRecord::Base
    has_secure_password
    has_many :posts

 validates :fullname, presence: true
 validates :username, presence: true, format:  {with: /@/, message: 'is not valid'}
 validates :password, presence:true
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :moderator
  has_many :post_tags, dependent: :destroy
  has_many :tags, through:  :post_tags
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true



#refactoring
  def self.matching_title_or_content search
    where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%")
end

end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ActiveRecord::Base
def self.site_name
    Setting.first.site_name
end
def self.post_per_page
    Setting.first.post_per_page
end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :posts, through:  :post_tags
    validates :name, presence: true
    def in_use?
        PostTag.exists?(tag_id: self.id)
    end
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
    has_many :notifications, as: :notifiable, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :messages, dependent: :destroy
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::ApplicationController
  def new
    @tag =Tag.new
    @tags =Tag.all.order(id: :desc).page params[:page]
  end

  def create
    tags_params[:name].split(',').map do |n|
      Tag.new(name: n).save
    end
    redirect_to new_admin_tag_url, notice: 'Tag was successfully created'
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update tags_params
      redirect_to new_admin_tag_url, notice: 'Tag was successfully updated'

else
  flash[:alert] = 'There was problem update tag'
  render  :edit
  end
  end

  def show
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to :back, notice: 'The tag deleted successfully'
  end
  private
  def tags_params

    params.require(:tag).permit(:id, :name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.where(publish: true).order(id: :desc).page(params[:page]).per(Setting.post_per_page)
  end

  def show
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
    def message_weight message
        message.status == false ? 'font-weight:bold' : 'font-weight:normal'
end
 def build_read_status_link message
    if message.status == true
        link_to 'Unread', admin_message_path(message, status: false), method: :put
    else
        link_to 'Read', admin_message_path(message, status: true), method: :put
    end
end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
    def create_deletable_button tag

                 if tag.in_use?
                  link_to '#' do
                          content_tag(:button, 'Delete', class: 'disabled')
                         end
                          else
                  link_to  admin_tag_path(tag), method:  :delete do
                    content_tag(:button, 'Delete')
                   end
                  end
              end

end

app/helpers/admin/visitors_helper.rb
module Admin::VisitorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def status_converter(status, truthy: 'Active', falsey: 'Pending')
        if status
            truthy
        else
            falsey
        end
    end
    def time_ago time_ago
        "#{time_ago_in_words(time)} ago"
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/tags/_tag_new.html.erb
 <div class="row">
            <div class="col-md-4 dashboard-left-cell">
              <div class="admin-content-con">
                <header>
                  <h5>Create Tags</h5>
                </header>
              <%=form_for [:admin, @tag] do |f| %>
                  <div class="form-group">
                    <label>add tags separeted by comma below</label>
                    <p>
                      <%= f.text_area :name, placeholder: 'e.g Ruby, Python, Php' %>
                    </p>
                    <p>
                    <%= f.submit %>
                    </p>
                  </div>
                <% end %>
              </div>
            </div>
             <div class="col-md-8 dashboard-right-cell">
              <div class=admin-content-con>
                <header>
                  <h5>Tags</h5>
                </header>
                <table class="table table-striped table-hover">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Status</th>
                      <th>Created</th>
                      <th>Actions</th>

                    </tr>
                  </thead>
                  <tbody>
                    <% @tags.each do |tag|  %>
                    <tr>
                      <td><%= tag.name %></td>
                      <td><% if tag.in_use? %>
                   <%= link_to '#' do %>
                      <span class="label label-success">in use</span>
                      <% end %>
                    <% else %>
                      <%= link_to '#' do %>
                    <span class="label label-warning">not use</span>
                    <% end %>
                    <% end %></td>
                      <td><%= time_ago_in_words tag.created_at %> ago</td>
                      <td>
                         <%= link_to  edit_admin_tag_path (tag) do %>
                              <button type ="button">Edit</button>
                               <% end %>

                           <%= create_deletable_button tag %>

                      </td>
                    </tr>
                                <% end %>
                  </tbody>
                </table>
              </div>

            </div>
          </div>
<P><%= paginate @tags %></P>

app/views/admin/tags/edit.html.erb
 <!DOCTYPE html>
<html>
<head>
  <title>BLOG</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= stylesheet_link_tag('backend', :media=> 'all') %>
    <%= stylesheet_link_tag('article', :media=> 'all') %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'adarticle', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'javascripts/admin/backend', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



  <div class="container-fluid display-table">

        <!-- side menu -->
      <%= render "admin/side_menu"%>

          <div class="col-md-10 col-sm-11 display-table-cell vertical-align">
       <div class="row">

               <header id="nav-header" class="clearfix">
                <div class="col-md-5">

                  <nav class="navbar-default pull-left">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="side-menu">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </nav>
                 <input type="text" class="hidden-sm hidden-xs" id="header-search-field" placeholder="search for anythings..">
                </div>
                  <div class="col-md-7">
                    <ul class="pull-right">
                      <li id="welcome" class="hidden-xs">welcome to administrator area</li>
                       <li class="fixed-width">
                        <a href="#">
                          <span class="glyphicon glyphicon-bell" aria-hidden="true"></span>
                          <span class="label label-warning">3</span>
                        </a>
                      </li>

                       <li class="fixed-width">
                        <a href="#">
                          <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                          <span class="label label-message">3</span>
                        </a>
                      </li>

                       <li>
                        <%=link_to logout_path do %>
                          <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                        log-out
                        <% end %>
                      </li>

                    </ul>

                  </div>
               </header>
           </div>


          <h1>Admin::Tags#edit</h1>
<%= form_for [:admin, @tag] do |f| %>
<p>
    <%=f.label :name %>
</p>
<p>
<%=f.text_field :name %>
</p>
<p><%=f.submit %></p>

<% end %>


           <div class="row">
            <footer id="admin-footer"  class="clearfix">
              <div class="pull-left"><b>copyright </b>&copy; 2016</div>
              <div class="pull-right">Shalo</div>
            </footer>

          </div>

</div>


<% yield %>

</body>

app/views/admin/tags/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BLOG</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= stylesheet_link_tag('backend', :media=> 'all') %>
    <%= stylesheet_link_tag('article', :media=> 'all') %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'article', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'backend', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



  <div class="container-fluid display-table">

        <!-- side menu -->
      <%= render "admin/side_menu"%>

          <div class="col-md-10 col-sm-11 display-table-cell vertical-align">
       <div class="row">

               <header id="nav-header" class="clearfix">
                <div class="col-md-5">

                  <nav class="navbar-default pull-left">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="side-menu">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </nav>
                 <input type="text" class="hidden-sm hidden-xs" id="header-search-field" placeholder="search for anythings..">
                </div>
                  <div class="col-md-7">
                    <ul class="pull-right">
                      <li id="welcome" class="hidden-xs">welcome to administrator area</li>
                       <li class="fixed-width">
                        <a href="#">
                          <span class="glyphicon glyphicon-bell" aria-hidden="true"></span>
                          <span class="label label-warning">3</span>
                        </a>
                      </li>

                       <li class="fixed-width">
                        <a href="#">
                          <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                          <span class="label label-message">3</span>
                        </a>
                      </li>

                       <li>
                        <%=link_to logout_path do %>
                          <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                        log-out
                        <% end %>
                      </li>

                    </ul>

                  </div>
               </header>
           </div>



 <div class="row">
            <div class="col-md-4 dashboard-left-cell">
              <div class="admin-content-con">
                <header>
                  <h5>Create Tags</h5>
                </header>
              <%=form_for [:admin, @tag] do |f| %>
                  <div class="form-group">
                    <label>add tags separeted by comma below</label>
                    <p>
                      <%= f.text_area :name, placeholder: 'e.g Ruby, Python, Php' %>
                    </p>
                    <p>
                    <%= f.submit %>
                    </p>
                  </div>
                <% end %>
              </div>
            </div>
             <div class="col-md-8 dashboard-right-cell">
              <div class=admin-content-con>
                <header>
                  <h5>Tags</h5>
                </header>
                <table class="table table-striped table-hover">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Status</th>
                      <th>Created</th>
                      <th>Actions</th>

                    </tr>
                  </thead>
                  <tbody>
                    <% @tags.each do |tag|  %>
                    <tr>
                      <td><%= tag.name %></td>
                      <td><% if tag.in_use? %>
                   <%= link_to '#' do %>
                      <span class="label label-success">in use</span>
                      <% end %>
                    <% else %>
                      <%= link_to '#' do %>
                    <span class="label label-warning">not use</span>
                    <% end %>
                    <% end %></td>
                      <td><%= time_ago_in_words tag.created_at %> ago</td>
                      <td>
                         <%= link_to  edit_admin_tag_path (tag) do %>
                              <button type ="button">Edit</button>
                               <% end %>

                           <%= create_deletable_button tag %>

                      </td>
                    </tr>
                                <% end %>
                  </tbody>
                </table>
              </div>

            </div>
          </div>



           <div class="row">
            <footer id="admin-footer"  class="clearfix">
              <div class="pull-left"><b>copyright </b>&copy; 2016</div>
              <div class="pull-right">Shalo</div>
            </footer>

          </div>

</div>


<% yield %>

</body>
<P><%= paginate @tags %></P>

app/views/admin/tags/show.html.erb
<h1>Admin::Tags#show</h1>
<p>Find me in app/views/admin/tags/show.html.erb</p>